name: Check and build application

on:
  push:
    branches:
      - '*'

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18.13.0'

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
