name: Check and build application

on:
  push:
    branches:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build


  format-code:
    runs-on: ubuntu-latest
    needs: [compile]
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main')
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Format code with prettier
        run: npm run prettier
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          message: "Code format with prettier"
          author_email: "Daniele Matta"